--vim.api.nvim_set_keymap('n', '<leader>ff', ':Files<CR>', {noremap=true})
--vim.api.nvim_set_keymap('n', '<leader>fg', ':GitFiles<CR>', {noremap=true})
--vim.api.nvim_set_keymap('n', '<leader>fr', ':Rg<CR>', {noremap=true})
--vim.api.nvim_set_keymap('n', '<leader>fb', ':Buffers<CR>', {noremap=true})
