#! /bin/sh

$HOME/.config/polybar/launch.sh &

# bspc monitor -d 1 2 3 4 5 6 6 8 9 10
bspc monitor -d         ﭮ 

bspc config border_width         2
bspc config window_gap           6

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false

# bspc rule -a Gimp state=floating follow=on
bspc rule -a Vlc state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Inkscape state=floating
bspc rule -a matplotlib state=floating
bspc rule -a Yad state=floating
bspc rule -a Sxiv state=floating
bspc rule -a \  state=floating
bspc rule -a Thunar state=floating
bspc rule -a minecraft-launcher state=floating

# Default desktops
bspc rule -a TelegramDesktop desktop=^10 follow=on
bspc rule -a Discord desktop=^9 follow=on
